---
# ESP 32
# https://docs.platformio.org/en/latest/boards/espressif32/esp32dev.html
# https://www.aliexpress.com/item/4001212139118.html
#
esphome:
  <<: !include .esphome.yaml
  platform: ESP32
  board: esp32dev