---
# Wi-Fi component package
#
# Contains my common Wi-Fi setup.
#
# https://esphome.io/components/wifi.html
#
substitutions:
  wifi_ssid: !secret iot_wifi_ssid
  wifi_password: !secret iot_wifi_pass
  wifi_ap_password: "esphome-${slug}"

wifi:
  id: component_wifi
  ssid: "${wifi_ssid}"
  password: "${wifi_password}"
  domain: .iot.local
  reboot_timeout: 10min
  ap:
    ssid: "${name}"
    password: "${wifi_ap_password}"

sensor:
  - <<: !include ../sensors/wifi_signal_percentage.yaml
  - <<: !include ../sensors/wifi_signal.yaml
    on_value:
      - component.update: sensor_wifi_signal_percentage

text_sensor:
  - <<: !include ../text_sensors/wifi_info.yaml